name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: appdb
        ports:
          - 5432:5432
      mongo:
        image: mongo:6
        ports:
          - 27017:27017

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build containers
      run: docker-compose -f docker-compose.yml build

    - name: Start containers
      run: docker-compose -f docker-compose.yml up -d

    # Example: Run backend tests
    - name: Run backend tests
      run: |
        docker-compose exec backend pytest  # Or your test command

    # Example: Run frontend tests
    - name: Run frontend tests
      run: |
        docker-compose exec frontend npm test  # Or your test command

    - name: Tear down
      run: docker-compose -f docker-compose.yml down

  # Deploy job (add your deployment steps/platform here)
  # deploy:
  #   needs: build-and-test
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Deploy to <your platform>
  #     run: echo "Add deployment steps here"